# Generated by Django 4.0.4 on 2022-07-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='EndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='StartTime',
            field=models.DateTimeField(null=True),
        ),
    ]
